### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by splagemann**
To add another docker-start script in `package.json` is probably not the best solution, but I didn't manage to inject `--host 0.0.0.0` in a different way

### CODE REVIEW

**Comment by feychou** [comment]
Is this needed in the docs too?

**Comment by splagemann** [comment]
Don't know. If you don't want to you can remove that from the docs. Was just creating a docker version out of fun 😄

**Comment by feychou** [comment]
There is another project in the project which is called `docs` and has its own package, I wonder whether that should that be referred to in the config or have its own config.

**Comment by splagemann** [comment]
Just tested that and it's working with the current config. Also references it in the README

**Pull request closed without merging**
